<!-- resources/views/pdf/footer.blade.php -->
<!-- Page footer with the user info and current date -->
<div class="footer">
    <p>Generated by {{ $user->name }} on {{ now()->toFormattedDateString() }}</p>
</div>

</body>
</html>
